name: Migrate Developer Portal (Dev to QA) - Python

on:
  workflow_dispatch:
    inputs:
      source_environment:
        description: 'Choose the source environment'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      target_environment:
        description: 'Choose the destination environment'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  capture_from_source:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.source_environment }}
    outputs:
      artifact_name: portal-content-${{ github.run_id }}
    steps:
      - name: 'Checkout Unified Repository'
        uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Setup Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 'Install Dependencies'
        run: pip install -r requirements.txt
        working-directory: ${{ github.workspace }}/python_migration

      

      - name: 'Capture Content from Source (Dev) APIM'
        run: |
          python ${{ github.workspace }}/python_migration/capture.py \
            --folder "${{ github.workspace }}/dist" \
            --env-file "${{ github.workspace }}/python_migration/.env.${{ github.event.inputs.source_environment }}"
        
      - name: 'Upload Portal Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: portal-content-${{ github.run_id }}
          path: ${{ github.workspace }}/dist/

  generate_to_target:
    needs: capture_from_source
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_environment }}
    steps:
      - name: 'Checkout Unified Repository'
        uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: 'Setup Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 'Download Portal Artifact'
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.capture_from_source.outputs.artifact_name }}
          path: ${{ github.workspace }}/dist/

      - name: 'Install Dependencies'
        run: pip install -r requirements.txt
        working-directory: ${{ github.workspace }}/python_migration

      

      - name: 'Generate Content to Destination APIM'
        run: |
          python ${{ github.workspace }}/python_migration/generate.py \
            --folder "${{ github.workspace }}/dist" \
            --env-file "${{ github.workspace }}/python_migration/.env.${{ github.event.inputs.target_environment }}"

      - name: 'Final Step: Manual Publish Required'
        run: |
          echo "Migration scripts completed successfully."
          echo "Please go to the Azure Portal for the destination APIM and publish the changes to make them live."
