name: Migrate Developer Portal (Dev to QA) - Python

on:
  workflow_dispatch:
    inputs:
      source_environment:
        description: 'Choose the source environment'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      target_environment:
        description: 'Choose the destination environment'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      publish_description:
        description: 'Enter a description for the publish action'
        required: false
        type: string

jobs:
  capture_from_source:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.source_environment }}
    outputs:
      artifact_name: portal-content-${{ github.run_id }}
    steps:
      - name: 'Checkout Unified Repository'
        uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Setup Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 'Install Dependencies'
        run: pip install -r requirements.txt
        working-directory: ${{ github.workspace }}/python_migration

      

      - name: 'Capture Content from Source (Dev) APIM'
        run: |
          python ${{ github.workspace }}/python_migration/capture.py \
            --folder "${{ github.workspace }}/dist" \
            --env-file "${{ github.workspace }}/python_migration/.env.${{ github.event.inputs.source_environment }}"
        
      - name: 'Upload Portal Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: portal-content-${{ github.run_id }}
          path: ${{ github.workspace }}/dist/

  generate_to_target:
    needs: capture_from_source
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_environment }}
    steps:
      - name: 'Checkout Unified Repository'
        uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: 'Setup Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 'Download Portal Artifact'
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.capture_from_source.outputs.artifact_name }}
          path: ${{ github.workspace }}/dist/

      - name: 'Install Dependencies'
        run: pip install -r requirements.txt
        working-directory: ${{ github.workspace }}/python_migration

      

      - name: 'Generate Content to Destination APIM'
        run: |
          python ${{ github.workspace }}/python_migration/generate.py \
            --folder "${{ github.workspace }}/dist" \
            --env-file "${{ github.workspace }}/python_migration/.env.${{ github.event.inputs.target_environment }}"

      - name: 'Publish Developer Portal'
        id: publish
        run: |
          ENV_FILE="${{ github.workspace }}/python_migration/.env.${{ github.event.inputs.target_environment }}"
          
          RESOURCE_GROUP_NAME=$(grep -oP '(?<=RESOURCE_GROUP_NAME=).*' "$ENV_FILE")
          SERVICE_NAME=$(grep -oP '(?<=SERVICE_NAME=).*' "$ENV_FILE")
          SUBSCRIPTION_ID=$(grep -oP '(?<=SUBSCRIPTION_ID=).*' "$ENV_FILE")
          API_VERSION="2024-05-01"
          
          PORTAL_REVISION_TO_PUBLISH=$(date -u +"%Y%m%d%H%M%S")
          PUBLISH_DESCRIPTION="${{ github.event.inputs.publish_description || format('Publishing revision {0}', PORTAL_REVISION_TO_PUBLISH) }}"
          
          echo "Attempting to publish developer portal revision: ${PORTAL_REVISION_TO_PUBLISH}"
          
          az rest --method put \
            --uri "https://management.azure.com/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP_NAME}/providers/Microsoft.ApiManagement/service/${SERVICE_NAME}/portalRevisions/${PORTAL_REVISION_TO_PUBLISH}?api-version=${API_VERSION}" \
            --body "{\"properties\": {\"description\": \"${PUBLISH_DESCRIPTION}\", \"isCurrent\": true}}"
          
          echo "Publish command initiated for revision ${PORTAL_REVISION_TO_PUBLISH}. Please allow a few minutes for changes to propagate."
          echo "You can check the status in the Azure portal under Developer portal -> Portal overview -> Revisions tab."

      
